import * as React from "react";

declare module "lucide-react" {
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
    className?: string;
  }

  export type LucideIcon = React.ComponentType<LucideProps>;

  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Mail: LucideIcon;
  export const Lock: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Loader2: LucideIcon;
  export const User: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const FileText: LucideIcon;
  export const X: LucideIcon;
  export const Shield: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Check: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const Search: LucideIcon;
  export const Bell: LucideIcon;
  export const Globe: LucideIcon;
  export const Sparkles: LucideIcon;

  export const Zap: LucideIcon;
  export const ZapOff: LucideIcon;
  export const Brain: LucideIcon;
  export const Activity: LucideIcon;
  export const BarChart: LucideIcon;
  export const BarChart2: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Clock: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Info: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const BookOpen: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Share2: LucideIcon;
  export const Filter: LucideIcon;
  export const Sliders: LucideIcon;

  export const Layout: LucideIcon;
  export const Settings: LucideIcon;
  export const UserCheck: LucideIcon;
  export const Heart: LucideIcon;
  export const Bookmark: LucideIcon;
  export const History: LucideIcon;
  export const Users: LucideIcon;
  export const Building: LucideIcon;
  export const Building2: LucideIcon;
  export const Plus: LucideIcon;
  export const Award: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const HeartCircle: LucideIcon;
  export const ThumbsUp: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Calendar: LucideIcon;
  export const Flame: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const Send: LucideIcon;
  export const Linkedin: LucideIcon;
  export const Twitter: LucideIcon;
  export const Instagram: LucideIcon;
  export const Youtube: LucideIcon;
  export const Facebook: LucideIcon;
  export const Edit2: LucideIcon;
  export const Star: LucideIcon;
  export const Trophy: LucideIcon;
  export const Medal: LucideIcon;
  export const BadgeCheck: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const Key: LucideIcon;
  export const KeyRound: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const Circle: LucideIcon;
  export const MapPin: LucideIcon;
  export const Download: LucideIcon;
  export const Bot: LucideIcon;
  export const LogIn: LucideIcon;
  export const LogOut: LucideIcon;
  export const UserPlus: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Moon: LucideIcon;
  export const Sun: LucideIcon;
  export const Newspaper: LucideIcon;
  export const Globe2: LucideIcon;
  export const UserCircle: LucideIcon;
  export const Crown: LucideIcon;
  export const Megaphone: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Landmark: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Calculator: LucideIcon;
  export const Phone: LucideIcon;
  export const Image: LucideIcon;
  export const Layers: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Play: LucideIcon;
  export const Microscope: LucideIcon;

  export const FlaskConical: LucideIcon;
  export const CircuitBoard: LucideIcon;
  export const Leaf: LucideIcon;
  export const Droplet: LucideIcon;
  export const Droplets: LucideIcon;
  export const Plane: LucideIcon;
  export const Mountain: LucideIcon;
  export const Radio: LucideIcon;
  export const Radar: LucideIcon;
  export const SunMedium: LucideIcon;
  export const TreePine: LucideIcon;
  export const Sprout: LucideIcon;
  export const Fish: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const UtensilsCrossed: LucideIcon;
  export const Tv: LucideIcon;
  export const Cog: LucideIcon;
  export const Wind: LucideIcon;
  export const Pill: LucideIcon;
  export const Ship: LucideIcon;
  export const BatteryCharging: LucideIcon;
  export const Rocket: LucideIcon;
  export const Store: LucideIcon;
  export const Recycle: LucideIcon;
  export const Truck: LucideIcon;
  export const Train: LucideIcon;
  export const Car: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const Target: LucideIcon;
  export const Package: LucideIcon;
  export const Monitor: LucideIcon;
  export const FileEdit: LucideIcon;
  export const Mic: LucideIcon;
  export const Mic2: LucideIcon;
  export const PenLine: LucideIcon;
  export const Handshake: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Microchip: LucideIcon;
  export const Pickaxe: LucideIcon;
  export const TestTube: LucideIcon;
  export const XCircle: LucideIcon;
  export const CornerDownRight: LucideIcon;
  export const Command: LucideIcon;
  export const FileDown: LucideIcon;
  export const Camera: LucideIcon;
  export const LayoutDashboard: LucideIcon;

  const content: any;
  export default content;
}
