import {
  Article,
  Sector,
  Country,
  LeaderDesignation,
  ContentType,
  ArticleStatus,
  BreakingNews,
} from "@/types/types";

// ==========================================
// SECTORS (20 as per spec)
// ==========================================
export const sectors: Sector[] = [
  { id: "s1", name: "Technology", slug: "technology", articleCount: 342, icon: "💻", trendingIndicator: "up" },
  { id: "s2", name: "Pharmaceuticals", slug: "pharmaceuticals", articleCount: 289, icon: "💊", trendingIndicator: "up" },
  { id: "s3", name: "Textiles & Apparel", slug: "textiles-apparel", articleCount: 198, icon: "🧵", trendingIndicator: "stable" },
  { id: "s4", name: "Automotive", slug: "automotive", articleCount: 256, icon: "🚗", trendingIndicator: "up" },
  { id: "s5", name: "Agriculture", slug: "agriculture", articleCount: 178, icon: "🌾", trendingIndicator: "stable" },
  { id: "s6", name: "Chemicals", slug: "chemicals", articleCount: 145, icon: "⚗️", trendingIndicator: "down" },
  { id: "s7", name: "Defence & Aerospace", slug: "defence-aerospace", articleCount: 167, icon: "🛡️", trendingIndicator: "up" },
  { id: "s8", name: "Electronics", slug: "electronics", articleCount: 234, icon: "📱", trendingIndicator: "up" },
  { id: "s9", name: "Energy & Power", slug: "energy-power", articleCount: 213, icon: "⚡", trendingIndicator: "up" },
  { id: "s10", name: "Food & Beverages", slug: "food-beverages", articleCount: 156, icon: "🍽️", trendingIndicator: "stable" },
  { id: "s11", name: "Gems & Jewellery", slug: "gems-jewellery", articleCount: 98, icon: "💎", trendingIndicator: "stable" },
  { id: "s12", name: "Healthcare", slug: "healthcare", articleCount: 267, icon: "🏥", trendingIndicator: "up" },
  { id: "s13", name: "Infrastructure", slug: "infrastructure", articleCount: 189, icon: "🏗️", trendingIndicator: "up" },
  { id: "s14", name: "Iron & Steel", slug: "iron-steel", articleCount: 123, icon: "🔩", trendingIndicator: "down" },
  { id: "s15", name: "Leather", slug: "leather", articleCount: 87, icon: "👜", trendingIndicator: "stable" },
  { id: "s16", name: "Marine & Shipping", slug: "marine-shipping", articleCount: 134, icon: "🚢", trendingIndicator: "stable" },
  { id: "s17", name: "Mining & Minerals", slug: "mining-minerals", articleCount: 112, icon: "⛏️", trendingIndicator: "down" },
  { id: "s18", name: "Plastics & Rubber", slug: "plastics-rubber", articleCount: 98, icon: "♻️", trendingIndicator: "stable" },
  { id: "s19", name: "Renewable Energy", slug: "renewable-energy", articleCount: 245, icon: "🌱", trendingIndicator: "up" },
  { id: "s20", name: "Services & IT", slug: "services-it", articleCount: 312, icon: "🖥️", trendingIndicator: "up" },
];

// ==========================================
// COUNTRIES (sample bilateral pairs)
// ==========================================
export const countries: Country[] = [
  { id: "c1", name: "USA", pairName: "USA–India", flagEmoji: "🇺🇸", tradeVolume: 128.5, articleCount: 456 },
  { id: "c2", name: "China", pairName: "China–India", flagEmoji: "🇨🇳", tradeVolume: 115.4, articleCount: 389 },
  { id: "c3", name: "UAE", pairName: "UAE–India", flagEmoji: "🇦🇪", tradeVolume: 84.2, articleCount: 234 },
  { id: "c4", name: "Saudi Arabia", pairName: "Saudi Arabia–India", flagEmoji: "🇸🇦", tradeVolume: 52.8, articleCount: 198 },
  { id: "c5", name: "Germany", pairName: "Germany–India", flagEmoji: "🇩🇪", tradeVolume: 28.4, articleCount: 167 },
  { id: "c6", name: "UK", pairName: "UK–India", flagEmoji: "🇬🇧", tradeVolume: 24.9, articleCount: 189 },
  { id: "c7", name: "Japan", pairName: "Japan–India", flagEmoji: "🇯🇵", tradeVolume: 21.3, articleCount: 145 },
  { id: "c8", name: "Singapore", pairName: "Singapore–India", flagEmoji: "🇸🇬", tradeVolume: 19.8, articleCount: 134 },
  { id: "c9", name: "Australia", pairName: "Australia–India", flagEmoji: "🇦🇺", tradeVolume: 18.2, articleCount: 112 },
  { id: "c10", name: "South Korea", pairName: "South Korea–India", flagEmoji: "🇰🇷", tradeVolume: 16.7, articleCount: 98 },
];

// ==========================================
// LEADER DESIGNATIONS (25 as per spec)
// ==========================================
export const leaderDesignations: LeaderDesignation[] = [
  { id: "l1", title: "CEO", priority: 1, articleCount: 456 },
  { id: "l2", title: "CFO", priority: 2, articleCount: 234 },
  { id: "l3", title: "CTO", priority: 3, articleCount: 198 },
  { id: "l4", title: "COO", priority: 4, articleCount: 178 },
  { id: "l5", title: "CMO", priority: 5, articleCount: 145 },
  { id: "l6", title: "Managing Director", priority: 6, articleCount: 312 },
  { id: "l7", title: "Chairman", priority: 7, articleCount: 289 },
  { id: "l8", title: "President", priority: 8, articleCount: 267 },
  { id: "l9", title: "Vice President", priority: 9, articleCount: 189 },
  { id: "l10", title: "Director", priority: 10, articleCount: 213 },
  { id: "l11", title: "Founder", priority: 11, articleCount: 345 },
  { id: "l12", title: "Co-Founder", priority: 12, articleCount: 234 },
  { id: "l13", title: "Board Member", priority: 13, articleCount: 123 },
  { id: "l14", title: "Partner", priority: 14, articleCount: 167 },
  { id: "l15", title: "Head of Strategy", priority: 15, articleCount: 134 },
  { id: "l16", title: "Head of Operations", priority: 16, articleCount: 112 },
  { id: "l17", title: "Head of Technology", priority: 17, articleCount: 156 },
  { id: "l18", title: "Head of Finance", priority: 18, articleCount: 98 },
  { id: "l19", title: "Head of Marketing", priority: 19, articleCount: 87 },
  { id: "l20", title: "Head of Sales", priority: 20, articleCount: 76 },
  { id: "l21", title: "General Manager", priority: 21, articleCount: 145 },
  { id: "l22", title: "Country Head", priority: 22, articleCount: 189 },
  { id: "l23", title: "Regional Director", priority: 23, articleCount: 112 },
  { id: "l24", title: "Chief Data Officer", priority: 24, articleCount: 67 },
  { id: "l25", title: "Chief Sustainability Officer", priority: 25, articleCount: 56 },
];

// ==========================================
// MOCK ARTICLES
// ==========================================
export const mockArticles: Article[] = [
  {
    id: "a1",
    slug: "india-semiconductor-push-2026",
    title: "India's ₹76,000 Crore Semiconductor Push: 3 New Fabs Approved, Production to Begin by 2027",
    summary: "The Indian government has approved three new semiconductor fabrication units in Gujarat, Karnataka, and Tamil Nadu, marking a historic shift in the country's electronics manufacturing ambitions. The move is expected to reduce India's dependency on chip imports by 40% within five years.",
    heroImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop",
    readTime: 7,
    type: ContentType.MANUAL_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    sector: sectors[0],
    sourceName: "IGN Editorial",
    authorName: "Priyanshi Sharma",
    likeCount: 468,
    commentCount: 52,
    shareCount: 71,
    isTrending: true,
    isBreaking: false,
    isSponsored: false,
    tags: ["Technology", "Semiconductor", "Manufacturing", "India", "Electronics"],
  },
  {
    id: "a2",
    slug: "pharma-exports-record-high",
    title: "Indian Pharma Exports Hit Record $28 Billion — Africa & Latin America Lead Growth",
    summary: "India's pharmaceutical exports crossed the $28 billion mark in FY2025-26, with Africa and Latin America emerging as the fastest-growing markets. Generic drug exports to sub-Saharan Africa grew 34% year-on-year.",
    heroImage: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=450&fit=crop",
    readTime: 5,
    type: ContentType.RSS_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    sector: sectors[1],
    country: countries[0],
    sourceName: "Economic Times",
    likeCount: 312,
    commentCount: 38,
    shareCount: 45,
    isTrending: true,
    isBreaking: false,
    isSponsored: false,
    tags: ["Pharmaceuticals", "Exports", "Africa", "Generic Drugs"],
  },
  {
    id: "a3",
    slug: "usa-india-trade-corridor",
    title: "USA–India Trade Corridor: New $2B Manufacturing Agreement Signed at G20 Side Event",
    summary: "A landmark $2 billion manufacturing partnership was signed between US and Indian trade bodies at the G20 side event in New Delhi, focusing on defense electronics, green hydrogen, and advanced materials. The agreement covers technology transfer and joint research programs.",
    heroImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=450&fit=crop",
    readTime: 6,
    type: ContentType.MANUAL_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    country: countries[0],
    sector: sectors[6],
    sourceName: "IGN Editorial",
    authorName: "Sanjay Mehta",
    likeCount: 289,
    commentCount: 45,
    shareCount: 62,
    isTrending: false,
    isBreaking: false,
    isSponsored: false,
    tags: ["USA", "India", "Trade", "Manufacturing", "Defence"],
  },
  {
    id: "a4",
    slug: "renewable-energy-100gw",
    title: "India Crosses 100GW Renewable Energy Milestone — Solar Leads at 67GW Installed Capacity",
    summary: "India has officially crossed the 100GW renewable energy capacity mark, with solar power contributing 67GW. The government's target of 500GW by 2030 is now considered achievable by industry analysts, supported by ₹19,500 crore PLI scheme for solar modules.",
    heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=450&fit=crop",
    readTime: 4,
    type: ContentType.RSS_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    sector: sectors[18],
    sourceName: "Mint",
    likeCount: 534,
    commentCount: 67,
    shareCount: 89,
    isTrending: true,
    isBreaking: false,
    isSponsored: false,
    tags: ["Renewable Energy", "Solar", "Green", "Climate"],
  },
  {
    id: "a5",
    slug: "ceo-interview-tata-tech",
    title: "Exclusive: Tata Technologies CEO on Building India's EV Ecosystem — 'We're 5 Years Ahead of Schedule'",
    summary: "In an exclusive interview with India Global News, Tata Technologies CEO shares insights on India's electric vehicle revolution, the company's role in developing affordable EV platforms, and plans for a ₹5,000 crore R&D investment in battery technology.",
    heroImage: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=800&h=450&fit=crop",
    readTime: 12,
    type: ContentType.MANUAL_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    sector: sectors[3],
    leaderDesignation: leaderDesignations[0],
    sourceName: "IGN Editorial",
    authorName: "Ritu Patel",
    likeCount: 678,
    commentCount: 89,
    shareCount: 112,
    isTrending: true,
    isBreaking: false,
    isSponsored: false,
    tags: ["Automotive", "EV", "CEO", "Tata", "Leadership"],
  },
  {
    id: "a6",
    slug: "textile-exports-eu-fta",
    title: "India-EU FTA Breakthrough: Textile Exports Set for 25% Duty Reduction Starting April 2026",
    summary: "After 12 years of negotiations, India and the EU have reached a breakthrough on textile and apparel tariffs. The new Free Trade Agreement provisions will reduce duties by 25% on Indian textiles entering European markets, benefiting over 4,500 exporters.",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=450&fit=crop",
    readTime: 5,
    type: ContentType.RSS_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    sector: sectors[2],
    sourceName: "Business Standard",
    likeCount: 234,
    commentCount: 31,
    shareCount: 28,
    isTrending: false,
    isBreaking: false,
    isSponsored: false,
    tags: ["Textiles", "FTA", "EU", "Exports", "Trade Policy"],
  },
  {
    id: "a7",
    slug: "uae-india-bilateral-infra",
    title: "UAE Commits $10B to India's Smart Cities Infrastructure — 5 Cities Selected for Phase 1",
    summary: "The UAE has committed $10 billion in infrastructure investments for India's smart cities program. Phase 1 targets Ahmedabad, Pune, Hyderabad, Kochi, and Lucknow with projects spanning transportation, renewable energy, and digital governance.",
    heroImage: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=450&fit=crop",
    readTime: 6,
    type: ContentType.MANUAL_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    sector: sectors[12],
    country: countries[2],
    sourceName: "IGN Editorial",
    authorName: "Priyanshi Sharma",
    likeCount: 189,
    commentCount: 27,
    shareCount: 34,
    isTrending: false,
    isBreaking: false,
    isSponsored: false,
    tags: ["UAE", "Infrastructure", "Smart Cities", "Investment"],
  },
  {
    id: "a8",
    slug: "food-processing-pli",
    title: "Food Processing PLI Scheme 2.0: ₹10,900 Crore Approved for 120 Companies",
    summary: "The government has approved the second phase of the PLI scheme for food processing, allocating ₹10,900 crore to 120 companies. The scheme targets value-added products like ready-to-eat meals, organic food, and premium dairy for export markets.",
    heroImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=450&fit=crop",
    readTime: 4,
    type: ContentType.RSS_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    sector: sectors[9],
    sourceName: "NDTV Profit",
    likeCount: 145,
    commentCount: 19,
    shareCount: 22,
    isTrending: false,
    isBreaking: false,
    isSponsored: false,
    tags: ["Food Processing", "PLI", "Government", "FMCG"],
  },
  {
    id: "a9",
    slug: "japan-india-ev-battery",
    title: "Japan–India EV Battery Alliance: ₹15,000 Crore Joint Venture Announced by Honda and Tata Chemicals",
    summary: "Honda Motor Co. and Tata Chemicals have announced a ₹15,000 crore joint venture to manufacture next-generation lithium iron phosphate (LFP) batteries in Maharashtra. The facility is expected to produce 40GWh annually by 2029.",
    heroImage: "https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=800&h=450&fit=crop",
    readTime: 8,
    type: ContentType.MANUAL_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    sector: sectors[3],
    country: countries[6],
    sourceName: "IGN Editorial",
    authorName: "Sanjay Mehta",
    likeCount: 356,
    commentCount: 42,
    shareCount: 56,
    isTrending: true,
    isBreaking: false,
    isSponsored: false,
    tags: ["Japan", "India", "EV", "Battery", "Joint Venture"],
  },
  {
    id: "a10",
    slug: "defence-exports-milestone",
    title: "India's Defence Exports Cross ₹21,000 Crore — BrahMos & HAL Lead Global Orders",
    summary: "India's defence exports have crossed the ₹21,000 crore milestone, driven by BrahMos missile sales to the Philippines and Vietnam, and HAL's light combat aircraft orders from Malaysia and Egypt. The Ministry of Defence targets ₹35,000 crore in defence exports by 2029.",
    heroImage: "https://images.unsplash.com/photo-1540575861501-7cf05a4b125a?w=800&h=450&fit=crop",
    readTime: 6,
    type: ContentType.RSS_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    sector: sectors[6],
    sourceName: "LiveMint",
    likeCount: 423,
    commentCount: 56,
    shareCount: 78,
    isTrending: true,
    isBreaking: false,
    isSponsored: false,
    tags: ["Defence", "Exports", "BrahMos", "HAL", "Military"],
  },
  {
    id: "a11",
    slug: "it-services-ai-boom",
    title: "Indian IT Services Revenue to Hit $300B by 2027 — AI and GenAI Consulting Drive Growth",
    summary: "Industry body NASSCOM projects that Indian IT services revenue will reach $300 billion by 2027, up from $254 billion in 2025. The surge is driven by AI transformation consulting, cloud migration services, and cybersecurity, with GenAI projects contributing 15% of new deal values.",
    heroImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=450&fit=crop",
    readTime: 5,
    type: ContentType.RSS_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    sector: sectors[19],
    sourceName: "Financial Express",
    likeCount: 267,
    commentCount: 34,
    shareCount: 41,
    isTrending: false,
    isBreaking: false,
    isSponsored: false,
    tags: ["IT Services", "AI", "NASSCOM", "Technology", "Revenue"],
  },
  {
    id: "a12",
    slug: "green-hydrogen-saudi",
    title: "Saudi Arabia–India Green Hydrogen MoU: $5B Investment Pipeline Announced at Riyadh Energy Forum",
    summary: "Saudi Arabia and India have signed a Green Hydrogen MoU at the Riyadh Energy Forum, establishing a $5 billion investment pipeline for green hydrogen production, transportation, and storage infrastructure spanning both nations.",
    heroImage: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&h=450&fit=crop",
    readTime: 6,
    type: ContentType.MANUAL_AI,
    status: ArticleStatus.PUBLISHED,
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    sector: sectors[8],
    country: countries[3],
    sourceName: "IGN Editorial",
    authorName: "Ritu Patel",
    likeCount: 198,
    commentCount: 23,
    shareCount: 31,
    isTrending: false,
    isBreaking: false,
    isSponsored: false,
    tags: ["Saudi Arabia", "Green Hydrogen", "Energy", "MoU"],
  },
];

// ==========================================
// BREAKING NEWS
// ==========================================
export const breakingNews: BreakingNews[] = [
  {
    id: "bn1",
    headline: "BREAKING: India signs $2B semiconductor deal with Netherlands — ASML to set up training center in Bangalore",
    articleSlug: "india-semiconductor-push-2026",
  },
];

// ==========================================
// TRENDING ARTICLES (subset)
// ==========================================
export const trendingArticles = mockArticles
  .filter((a) => a.isTrending)
  .sort((a, b) => b.likeCount - a.likeCount);

// ==========================================
// MOST DISCUSSED (sorted by comments)
// ==========================================
export const mostDiscussedArticles = [...mockArticles]
  .sort((a, b) => b.commentCount - a.commentCount)
  .slice(0, 5);
